#  _                      _            _    
# | |__  _   _ _ __  _ __| | ___   ___| | __
# | '_ \| | | | '_ \| '__| |/ _ \ / __| |/ /
# | | | | |_| | |_) | |  | | (_) | (__|   < 
# |_| |_|\__, | .__/|_|  |_|\___/ \___|_|\_\
#        |___/|_|                           
# 

# Minimal GNOME-style Hyprlock
# For 1366x768 display
source= ~/.cache/wal/colors-hyprland.conf
# ===== GENERAL =====
general {
    no_fade_in = false
    no_fade_out = false
    grace = 0
    disable_loading_bar = false
    hide_cursor = false
}

animations {
    # Animation for the lock screen fade in/out
    animation = fadeIn, 1, 2, linear
}

# ===== BACKGROUND =====
background {
    monitor =
    path = ~/.config/hypr/current_hyprlock_wallpaper.jpg 
    blur_passes = 1
    blur_size = 6
    contrast = 0.9
    brightness = 0.75
    vibrancy = 0.15
}

# ===== TIME - HOUR =====
label {
    monitor =
    text = cmd[update:1000] echo "<span>$(date +"%I")</span>"
    color = $color14 
    font_size = 110
    font_family = JetBrains Mono Nerd
    position = -500, 199
    halign = center
    valign = center
}

# ===== TIME - MINUTE =====
label {
    monitor =
    text = cmd[update:1000] echo "<span>$(date +"%M")</span>"
    color = $color14
    font_size = 110
    font_family = JetBrains Mono Nerd
    position = -400, 96
    halign = center
    valign = center
}

# ===== DATE =====
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%d %B, %A")"
    color = $color14
    font_size = 18
    font_family = JetBrains Mono Nerd
    position = -450, 28
    halign = center
    valign = center
}

# ===== USERNAME =====
label {
    monitor =
    text = $USER
    color = $color14
    font_size = 21
    font_family = JetBrains Mono Nerd
    position = -450, -130
    halign = center
    valign = center
}

# ===== PASSWORD INPUT =====
input-field {
    monitor =
    size = 300, 45
    outline_thickness = 0
    dots_size = 0.25
    dots_spacing = 0.25
    dots_center = true
    outer_color = rgba(255, 255, 255, 0)
    inner_color = $color14
    font_color = rgba(255, 255, 255, 0.9)
    fade_on_empty = false
    font_family = JetBrains Mono Nerd
    placeholder_text = <span foreground="##ffffff99">password</span>
    hide_input = false
    rounding = 22
    position = -450, -180
    halign = center
    valign = center
}
# CURRENT SONG
label {
    monitor =
    text = cmd[update:1000] echo "$(~/.config/hypr/Scripts/songdetail.sh)" 
    color =  $color14
    font_size = 16
    font_family = JetBrains Mono Nerd
    position = 0, 50
    halign = center
    valign = bottom
}
